name: Weekly Link Checker

on:
  schedule:
    - cron: '0 8 * * 1'   # Runs every Monday at 8 AM UTC
  workflow_dispatch:      # Allow manual runs from GitHub UI
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install htmltest
        run: |
          go install github.com/wjdp/htmltest@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Build static site
        run: |
          npm ci
          npm run build
          npm run export

      - name: Run HTML link checker
        run: htmltest ./out